version: "3.7"

services:
  database:
    image: postgres
    container_name: adoption-db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=adoption
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local